export const TYPES = {
  DatabaseService: Symbol.for("DatabaseService"),
  Cloud115Service: Symbol.for("Cloud115Service"),
  QuarkService: Symbol.for("QuarkService"),
  Searcher: Symbol.for("Searcher"),
  DoubanService: Symbol.for("DoubanService"),
  ImageService: Symbol.for("ImageService"),
  SettingService: Symbol.for("SettingService"),
  UserService: Symbol.for("UserService"),
  SponsorsService: Symbol.for("SponsorsService"),

  Cloud115Controller: Symbol.for("Cloud115Controller"),
  QuarkController: Symbol.for("QuarkController"),
  ResourceController: Symbol.for("ResourceController"),
  DoubanController: Symbol.for("DoubanController"),
  ImageController: Symbol.for("ImageController"),
  SettingController: Symbol.for("SettingController"),
  UserController: Symbol.for("UserController"),
  SponsorsController: Symbol.for("SponsorsController"),
};
